apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp04
  namespace: fourier
  labels:
    app.oam.dev/sharding: sharding-2
spec:
  components:
    - name: fourierapp04-comp-01
      type: webservice
      properties:
        image: nginx:latest
        ports:
          - expose: true
            port: 80
            protocol: TCP
        imagePullPolicy: IfNotPresent
      traits:
        - type: scaler
          properties:
            replicas: 1

    - name: fourierapp04-comp-02
      type: webservice
      dependsOn:
        - fourierapp04-comp-01
      properties:
        image: nginx:latest
        ports:
          - expose: true
            port: 80
            protocol: TCP
        imagePullPolicy: IfNotPresent
      traits:
        - type: scaler
          properties:
            replicas: 1

  policies:
    - name: health-policy-01
      type: health
      properties:
        probeInterval: 30
        probeTimeout: 10
    - name: fourierapp04-comp-01
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: velero

  workflow:
    steps:
      - name: step-group
        type: step-group
        subSteps:
          - name: fourierapp04-deploy-01
            type: deploy
            properties:
              policies: [ "fourierapp04-comp-01" ]