apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp02
  namespace: fourier
spec:
  components:
    - name: fourierapp02-comp-01
      type: webservice
      properties:
        image: nginx:latest
        ports:
          - expose: true
            port: 80
            protocol: TCP
        imagePullPolicy: IfNotPresent
      traits:
        - type: scaler
          properties:
            replicas: 1

  policies:
    - name: fourierapp02-comp-01
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: fourier01
    - name: fourierapp02-comp-02
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: fourier02

  workflow:
    steps:
      - name: fourierapp02-deploy-01
        type: deploy
        #        失败重试
        #        retry:
        #          times: 5
        #          interval: "50"
        properties:
          policies: [ "fourierapp02-comp-01" ]
      - name: fourierapp02-deploy-02
        type: deploy
        #        retry:
        #          times: 3
        #          interval: "30"
        properties:
          policies: [ "fourierapp02-comp-02" ]