apiVersion: v1
kind: Service
metadata:
  labels:
    aaa: velero
  name: velero
  namespace: velero
spec:
  ports:
    - name: http-monitoring
      port: 8085
      protocol: TCP
      targetPort: http-monitoring
  selector:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/name: velero
    name: velero
  sessionAffinity: None
  type: ClusterIP