apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp03
  namespace: fourier
spec:
  components:
    - name: fourierapp03-fouriercomponent-01
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "10000" ]
        cpu: "0.1"
        mem: "100Mi"
      traits:
        - type: scaler
          properties:
            replicas: 1
        - type: ipodscaler
          properties:
            name: fourierapp03-ipodscaler-01
            scaleTargetRef:
              - cluster: local
                namespace: fourier01
              - cluster: local
                namespace: fourier02
            scaleStrategy: "DryRun"
            horizationPodAutoscaler:
              minReplicas: 1
              maxReplicas: 10
              metrics:
                - type: Resource
                  resource:
                    name: "cpu"
                    target:
                      type: Utilization
                      averageUtilization: 50
              crons:
                - name: "cron1"
                  timezone: "Local"
                  description: "scale down"
                  start: "0 0 ? * *"
                  end: "0 6 ? * *"
                  targetReplicas: 2
            prediction:
              predictionWindowSeconds: 3600
              predictionAlgorithm:
                algorithmType: dsp
                dsp:
                  sampleInterval: 60
                  historyLength: 3600
  policies:
    - name: fourierapp03-topology-01
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: fourier01
    - name: fourierapp03-topology-02
      type: topology
      properties:
        clusters: [ "local" ]
        namespace: fourier02
  #    - name: apply-once
  #      type: apply-once
  #      properties:
  #        enable: true
  #        component:
  #          - name: fourierapp03-fouriercomponent-01
  #            resource:
  #              - type: deployment
  #                path: spec.replicas
  workflow:
    steps:
      - type: deploy
        name: fourierapp03-deploy-01
        properties:
          policies: [ "fourierapp03-topology-01" ]
      - type: deploy
        name: fourierapp03-deploy-02
        properties:
          policies: [ "fourierapp03-topology-02" ]