apiVersion: autoscaling.oam.cmb/v1alpha1
kind: IntelligentPodAutoscaler
metadata:
  name: fouriercmbpa01
  namespace: lt31-04-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fourierapp01-comp-01
    namespace: lt31-04-dayu-test2
    cluster: csdev-biz-07-qh
  upDelay: 10
  downDelay: 10
  scaleStrategy: Auto/DryRun
  horizationPodAutoscaler:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      - type: Resource/Pods/Object/External
        resource:
          name: cpu/mem
          target:
            type: Utilization/averageValue/value
            averageUtilization: 50
    crons:
      - name: "cron1"
        timezone: "Local"
        description: "scale down"
        start: "0 0 ? * *"
        end: "0 6 ? * *"
        targetReplicas: 2
      - name: "cron2"
        timezone: "Local"
        description: "scale up"
        start: "0 6 ? * *"
        end: "0 9 ? * *"
        targetReplicas: 10
  verticalPodAutoscaler:
    minCPU: 1
    maxCPU: 1
    minMemory: 1
    maxMemory: 1
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 50
    crons:
      - name: "cron1"
        timezone: "Local"
        description: "scale down"
        start: "0 0 ? * *"
        end: "0 6 ? * *"
        targetMemory: 2Gi
        targetCPU: 2
  prediction:
    predictionWindowSeconds: 3600
    predictionAlgorithm:
      algorithmType: dsp
      dsp:
        sampleInterval: "60s"
        historyLength: "3d"

