// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_OK-0]
	_ = x[ERR_PARAMS-1]
	_ = x[ERR_TIMEOUT-2]
}

const _ErrCode_name = "请求OK请求参数出错请求超时"

var _ErrCode_index = [...]uint8{0, 8, 26, 38}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
