apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx-admission
webhooks:
  - name: validate.delete.ns
    matchPolicy: Exact
    rules:
      - apiGroups:
          - *
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - namespaces
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        namespace: vela-system
        name: ingress-nginx-controller-admission
        path: /validate/delete/ns
  - name: validate.delete.crd
    matchPolicy: Exact
    rules:
      - apiGroups:
          - apiextensions.k8s.io
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - customResourceDefinitions
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1beta1
    clientConfig:
      service:
        namespace: vela-system
        name: ingress-nginx-controller-admission
        path: /validate/delete/crd