apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: fourierapp03
  namespace: fourier
spec:
  components:
    - name: fourierapp03-comp-01
      type: webservice
      properties:
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        cmd: [ "sleep", "10000" ]
        cpu: "0.1"
        mem: "100Mi"
      traits:
        - type: scaler
          properties:
            replicas: 1
#  policies:
#    - name: fourierapp03-topology-01
#      type: topology
#      properties:
#        clusters: [ "local" ]
#        namespace: fourier01
#    - name: fourierapp03-topology-02
#      type: topology
#      properties:
#        clusters: [ "local" ]
#        namespace: fourier02
#    - name: apply-once-01
#      type: apply-once
#      properties:
#        enable: true
#        rules:
#          - selector:
#              componentNames: [ "fourierapp03-comp-01" ]
#              resourceTypes: [ "Deployment" ]
#            strategy:
#              path: [ "spec.replicas" ]

#  workflow:
#    steps:
#      - type: deploy
#        name: fourierapp03-deploy-01
#        properties:
#          policies: [ "fourierapp03-topology-01" ]
#      - type: deploy
#        name: fourierapp03-deploy-02
#        properties:
#          policies: [ "fourierapp03-topology-02" ]