apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    app.oam.dev/appAlias: fourier27
    app.oam.dev/appName: lt31-04-fourier27-dev-dev
    oam.dev/kubevela-version: v1.2.0
  creationTimestamp: "2022-09-22T13:15:31Z"
  finalizers:
  - app.oam.dev/resource-tracker-finalizer
  generation: 19
  labels:
    project: lt31.04
  name: lt31-04-fourier27-dev-dev
  namespace: lt31-04-dev
spec:
  components:
  - name: fourier27-web-270519
    properties:
      componentEnv:
        clusterType: COMMON-APP
        netRegion: OA
      convertComponent: ""
      env:
      - name: CMB_CAAS_OAM_COMP_NAME
        value: fourier27-web-dev-dev
      - name: CMB_CLUSTER
        value: csdev-biz-05-qh
      - name: CMB_CAAS_DEPLOYUNITID
        value: LT31.04_fourier27-web
      - name: CMB_CAAS_NAMESPACE
        value: lt31-04-dev-default
      - name: CMB_CAAS_APPLICATION
        value: fourier27-web-270519
      - name: CMB_CAAS_SERVICEUNITID
        value: LT31.04@fourier27-web_DEV_dev
      - name: CMB_PAAS_ENV
        value: DEV
      - name: CMB_CAAS_OAM_APP_NAME
        value: lt31-04-fourier27-dev-dev
      - name: CMB_CAAS_PROJECT
        value: lt31.04
      image: csdev.registry.cmbchina.cn/lt31.04/fourier27-web:pl260104-1
      labels:
        app.alauda.io/name: fourier27-web-270519.lt31-04-dev-default
        cmb: lt31.04
        cmb-app-name: fourier27-web-270519
        cmb-log-tag: lt31-04-dev-default-Deployment-fourier27-web-270519
        cmb-org: lt31.04
        cmb-service-unit-id: LT31.04...fourier27-web_DEV_dev
      matchLabels:
        app.alauda.io/name: fourier27-web-270519.lt31-04-dev-default
      namespace: lt31-04-dev-default-federation-csdev-biz-05
      ports:
      - port: 8082
    traits:
    - properties:
        limits:
          cpu: "0.5"
          memory: 0.5Gi
        replicas: 1
        requests:
          cpu: "0.5"
          memory: "357913941"
        execCPU: "0.5"
        execMemory: 0.5Gi
        execReplicas: 2
#        cronPodScaler:
#          - end: CRON_TZ=Asia/Shanghai 00 00 15 ? * 1,2,3,4,5,6,0
#            name: cron-qujxs
#            start: CRON_TZ=Asia/Shanghai 00 00 00 ? * 1,2,3,4,5,6,0
#            targetReplicas: 2
        metricPodScaler:
          metricTarget:
            metricReplicas: 1
            metricCPU: "1"
            metricMemory: "1Gi"
          triggers:
          - type: cpu
            metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
            value: 80
          - type: memory
            metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
            value: 80
            externalKey: JAVA-OPTS
            externalValue:
              jdkVersion: "1.8"
              reservedMemory: 10
              directMemory: 10
              heap: 65
              metaspace: 10
              native: 15
              stack: 10
        podScalerConfig:
          priorityStrategy: ReplicasFirst # ReplicasFirst or CPU&MemoryFirst
          cooldownPeriod: 600
          coolupPeriod: 60
          maxCPU: "8"
          maxMemory: "8Gi"
          maxReplicas: 8
          minCPU: "0.2"
          minMemory: "200Mi"
          minReplicas: 1
        shardingInfo: sharding-x
        scaleStrategy: Auto
        generateCR: true
      type: resources
    - properties:
        annotations:
          owners.alauda.io/info: '[{"name":"钟世杰","phone":"18306035163","employee_id":"80310287@itc"}]'
        labels:
          app.alauda.io/name: fourier27-web-270519.lt31-04-dev-default
          cmb-app-name: fourier27-web-270519
          cmb-service-unit-id: LT31.04...fourier27-web_DEV_dev
        matchLabels: null
      type: labels
    type: webservice
  policies:
  - name: fourier27-web-270519
    properties:
      clusters:
      - csdev-biz-05-qh
      - csdev-biz-05-sk
      namespace: lt31-04-dev-default
    type: topology
  workflow:
    steps:
    - name: lt31-04-fourier27-dev-dev
      subSteps:
      - name: fourier27-web-270519
        properties:
          component: fourier27-web-270519
          topologyPolicies:
          - fourier27-web-270519
        type: deploy-cmb-upcase
      type: step-group
