apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podscalers.scaler.oam.cmb
spec:
  group: scaler.oam.cmb
  scope: Namespaced
  names:
    kind: PodScaler
    listKind: PodScalerList
    singular: podscaler
    plural: podscalers
    shortNames:
      - ps
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: ApiVersion defines the versioned schema of this representation of an object
              type: string
            kind:
              description: Kind is a string value representing the REST resource this object represents
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                scaleStrategy:
                  type: string
                scaleTargetRef:
                  type: object
                  properties:
                    clusters:
                      type: string
                    namespace:
                      type: string
                    appName:
                      type: string
                    compName:
                      type: string
                    serviceUnitID:
                      type: string
                podScalerConfig:
                  type: object
                  properties:
                    priorityStrategy:
                      type: string
                    cooldownPeriod:
                      format: int32
                      type: integer
                    coolupPeriod:
                      format: int32
                      type: integer
                    minReplicas:
                      format: int32
                      type: integer
                    maxReplicas:
                      format: int32
                      type: integer
                    minCPU:
                      type: string
                    maxCPU:
                      type: string
                    minMemory:
                      type: string
                    maxMemory:
                      type: string
                cronPodScaler:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      timezone:
                        type: string
                      start:
                        type: string
                      end:
                        type: string
                      targetMemory:
                        type: string
                      targetCPU:
                        type: string
                      targetReplicas:
                        format: int32
                        type: integer
                      targetJAVAOPTS:
                        type: string
                metricPodScaler:
                  type: object
                  properties:
                    metricTarget:
                      type: object
                      properties:
                        metricReplicas:
                          format: int32
                          type: integer
                        metricCPU:
                          type: string
                        metricMemory:
                          type: string
                    triggers:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          metricType:
                            type: string
                          value:
                            format: int32
                            type: integer
                          externalKey:
                            type: string
                          externalValue:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true

            status:
              description: Most recently observed status of the Route
              type: object
              properties:
                phase:
                  type: string
                observedGeneration:
                  format: int64
                  type: integer
                message:
                  type: string
                revisionHash:
                  type: string
                scaleTarget:
                  type: object
                  properties:
                    updateTime:
                      type: string
                    targetMemory:
                      type: string
                    targetCPU:
                      type: string
                    targetReplicas:
                      format: int32
                      type: integer
                    targetJAVAOPTS:
                      type: string
                    restoreTarget:
                      type: boolean
                cronPodScaler:
                  type: object
                  properties:
                    updateTime:
                      type: string
                    targetMemory:
                      type: string
                    targetCPU:
                      type: string
                    targetReplicas:
                      format: int32
                      type: integer
                    targetJAVAOPTS:
                      type: string
                    restoreTarget:
                      type: boolean
                cronPodScalerStatus:
                  type: object
                  properties:
                    phase:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    message:
                      type: string
                    startCronMessage:
                      type: string
                    endCronMessage:
                      type: string
                metricPodScaler:
                  type: object
                  properties:
                    updateTime:
                      type: string
                    targetMemory:
                      type: string
                    targetCPU:
                      type: string
                    targetReplicas:
                      format: int32
                      type: integer
                    targetJAVAOPTS:
                      type: string
                    restoreTarget:
                      type: boolean
                metricPodScalerStatus:
                  type: object
                  properties:
                    phase:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    message:
                      type: string
          required:
            - apiVersion
            - kind
            - metadata
            - spec
      subresources:
        status: { }