apiVersion: v1
kind: Service
metadata:
  annotations:
    "service/config": "True"
  name: svc01
  namespace: default
spec:
  ports:
    - port: 9443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/instance: kubevela-cluster-gateway
    app.kubernetes.io/name: vela-core-cluster-gateway
  type: ClusterIP