apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: mytest
          image: nginx:v1
    metadata:
      labels:
        app.oam.dev/component: mytest
  selector:
    matchLabels:
      app.oam.dev/component: mytest
